#include "PCH.h"
#include "Fortify.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstring>
#include <functional>
#include <string>
#include <utility>
#include <vector>


#include "Settings.h"
#include "Util.h"
#include "logger.h"

// Comments are mostly generated by Claude, should be easy to differentiate
// Sources cited because I wouldn't have been able to make this mod otherwise

namespace
{
    using MOD = RE::ACTOR_VALUE_MODIFIERS::ACTOR_VALUE_MODIFIER;

    std::atomic<Fortify::Mode> g_mode{ Fortify::Mode::kAbsolute };
    std::atomic_bool g_playerOnly{ false };

    std::atomic_uint64_t g_seen{ 0 };
    std::atomic_uint64_t g_corrected{ 0 };
    std::atomic_uint64_t g_restores{ 0 };
    std::atomic_uint64_t g_deaths{ 0 };

#ifdef FF_DEBUG_PANEL
    // Samples left in an armed state burst, from the Debug page
    std::atomic_int32_t g_stateLogRemaining{ 0 };
#endif

    // Left room for more a couple more call sites
    constexpr std::size_t MAX_CALL_SITES = 8;

    // Small enough to be invisible, large enough not to vanish into float noise. Applied in the safe direction first, so the intermediate state is never more damaged than the corrected one
    constexpr float ARM_NUDGE = 0.05f;

    // Not REX::W32::MAX_PATH, the Windows macro expands first
    constexpr std::size_t MODULE_PATH_MAX = 260;

    // Counted on unpacked 1.6.1170
    // I'm assuming this is going to be the same for 1.7.X
    constexpr std::size_t EXPECTED_CALL_SITES = 6;

    std::uintptr_t g_publishedSites[5]{};
    std::vector<Fortify::CallSite> g_callSites;
    std::size_t g_installed{ 0 };

    // Only the three pooled attributes carry a damage modifier that can outlive its maximum
    [[nodiscard]] RE::Modifiers* SlotsFor(RE::Actor* a_actor, RE::ActorValue a_av)
    {
        auto& data = a_actor->GetActorRuntimeData();
        switch (a_av) {
        case RE::ActorValue::kHealth:
            return &data.healthModifiers;
        case RE::ActorValue::kMagicka:
            return &data.magickaModifiers;
        case RE::ActorValue::kStamina:
            return &data.staminaModifiers;
        default:
            return nullptr;
        }
    }

    struct Snapshot
    {
        float permanent{ 0.0f };
        float temporary{ 0.0f };
        float damage{ 0.0f };
        float current{ 0.0f };

        // Maximum is everything except the damage the actor has taken
        [[nodiscard]] float Maximum() const { return current - damage; }
    };

    // A raw slot write leaves the derived value cached, so the engine keeps handing out the old one until something recalculates (Styyx1/ResurrectionAPI-po3Clib/src/main.cpp:96-121)
    void InvalidateCached(RE::Actor* a_actor, RE::ActorValue a_av)
    {
        using func_t = void(RE::Actor*, RE::ActorValue);
        static REL::Relocation<func_t> func{ RELOCATION_ID(37534, 38483) };
        func(a_actor, a_av);
    }

    // The whole correction, as a pure function of the two snapshots. Each mode is one branch, and none of them can reach anything but the damage slot
    [[nodiscard]] float WantedDamage(const Snapshot& a_before, float a_maxAfter)
    {
        const float maxBefore = a_before.Maximum();

        // A ravage plus accumulated damage can put the engine's arithmetic below zero, and preserving that would write back a value the actor never actually held
        const float beforeCurrent = std::max(0.0f, a_before.current);

        // Only on the way up, so an effect that reapplies itself on a tick cannot keep refilling the actor, and so a ravage lowering the maximum still falls through to preservation
        if (g_mode.load() == Fortify::Mode::kRestore && a_maxAfter > maxBefore) {
            return 0.0f;
        }

        if (g_mode.load() == Fortify::Mode::kRatio) {
            if (maxBefore <= 0.0f) {
                return a_before.damage;
            }
            const float ratio = beforeCurrent / maxBefore;
            return std::min(0.0f, a_maxAfter * ratio - a_maxAfter);
        }

        return std::min(0.0f, beforeCurrent - a_maxAfter);
    }

    // The call sites run inside the engine's modifier function before it applies anything, so the compensation lands first and the value never computes below zero

    // A fortify lives above zero and a ravage below it, so only movement in positive territory is one. Handing a ravage's points back as it leaves is vanilla behaviour, not a bug to correct
    [[nodiscard]] float FortifyPart(float a_before, float a_after)
    {
        return std::max(0.0f, a_after) - std::max(0.0f, a_before);
    }

#ifdef FF_DEBUG_PANEL
    // Logged before any early return, so a kDamage regeneration tick shows up as readily as a fortify
    void LogState(RE::Actor* a_actor, MOD a_mod, RE::ActorValue a_av, float a_delta)
    {
        if (g_stateLogRemaining <= 0 || a_actor != RE::PlayerCharacter::GetSingleton()) {
            return;
        }

        auto* slots = SlotsFor(a_actor, a_av);
        if (!slots) {
            return;
        }
        --g_stateLogRemaining;

        auto* process = a_actor->GetActorRuntimeData().currentProcess;
        auto* high = process ? process->high : nullptr;

        static constexpr const char* SLOT[]{ "perm", "temp", "dmg" };
        logger::info("state av {} {} {:+.2f} | perm {:.1f} temp {:.1f} dmg {:.1f} cur {:.1f} | delays h {:.2f} s {:.2f} m {:.2f} | {} left",
                     static_cast<int>(a_av), a_mod <= MOD::kDamage ? SLOT[a_mod] : "?", a_delta,
                     slots->modifiers[MOD::kPermanent], slots->modifiers[MOD::kTemporary],
                     slots->modifiers[MOD::kDamage],
                     a_actor->AsActorValueOwner()->GetActorValue(a_av),
                     high ? high->healthRegenDelay : -1.0f, high ? high->staminaRegenDelay : -1.0f,
                     high ? high->magickaRegenDelay : -1.0f, g_stateLogRemaining.load());
    }

    // All three attributes, not just the one that moved, so a cause nobody has thought of still leaves a fingerprint
    // My saviour
    void LogSnapshot(const char* a_why)
    {
        auto* player = RE::PlayerCharacter::GetSingleton();
        if (!player) {
            return;
        }

        auto* owner = player->AsActorValueOwner();
        auto& rt = player->GetActorRuntimeData();
        auto* process = rt.currentProcess;
        auto* high = process ? process->high : nullptr;

        const auto line = [&](const char* a_tag, RE::ActorValue a_av, RE::Modifiers& a_slots,
                              RE::ActorValue a_rate, RE::ActorValue a_mult, float a_delay) {
            logger::info("snap {} {} base {:.1f} perm {:.1f} temp {:.1f} dmg {:.1f} cur {:.1f} | rate {:.2f} mult {:.1f} delay {:.2f}",
                         a_why, a_tag, owner->GetBaseActorValue(a_av),
                         a_slots.modifiers[MOD::kPermanent], a_slots.modifiers[MOD::kTemporary],
                         a_slots.modifiers[MOD::kDamage], owner->GetActorValue(a_av),
                         owner->GetActorValue(a_rate), owner->GetActorValue(a_mult), a_delay);
        };

        line("H", RE::ActorValue::kHealth, rt.healthModifiers, RE::ActorValue::kHealRate,
             RE::ActorValue::kHealRateMult, high ? high->healthRegenDelay : -1.0f);
        line("M", RE::ActorValue::kMagicka, rt.magickaModifiers, RE::ActorValue::kMagickaRate,
             RE::ActorValue::kMagickaRateMult, high ? high->magickaRegenDelay : -1.0f);
        line("S", RE::ActorValue::kStamina, rt.staminaModifiers, RE::ActorValue::kStaminaRate,
             RE::ActorValue::kStaminaRateMult, high ? high->staminaRegenDelay : -1.0f);

        logger::info("snap {} | combat {} | high {} | combatHealthRegenMult {:.2f} | paused {}", a_why,
                     player->IsInCombat(), high != nullptr,
                     owner->GetActorValue(RE::ActorValue::kCombatHealthRegenMultiply),
                     RE::UI::GetSingleton() ? RE::UI::GetSingleton()->GameIsPaused() : false);
    }

#else
    void LogState(RE::Actor*, MOD, RE::ActorValue, float) {}
#endif

    // Returns whether it wrote, so the caller knows to arm regeneration afterwards
    bool OnModifierChange(RE::Actor* a_actor, MOD a_mod, RE::ActorValue a_av, float a_delta)
    {
        if (!a_actor) {
            return false;
        }

        LogState(a_actor, a_mod, a_av, a_delta);

        if (g_mode.load() == Fortify::Mode::kOff) {
            return false;
        }
        if (a_mod != MOD::kPermanent && a_mod != MOD::kTemporary) {
            return false;
        }

        auto* slots = SlotsFor(a_actor, a_av);
        if (!slots) {
            return false;
        }
        if (g_playerOnly.load() && !a_actor->IsPlayerRef()) {
            return false;
        }

        const float before = slots->modifiers[a_mod];
        const float rise = FortifyPart(before, before + a_delta);

        ++g_seen;
        if (std::abs(rise) < 0.001f) {
            ++g_restores;
            return false;
        }

        auto* owner = a_actor->AsActorValueOwner();
        const float damage = slots->modifiers[MOD::kDamage];
        const float maxBefore = owner->GetBaseActorValue(a_av) + slots->modifiers[MOD::kPermanent] +
                                slots->modifiers[MOD::kTemporary];

        const Snapshot before_{ slots->modifiers[MOD::kPermanent], slots->modifiers[MOD::kTemporary], damage,
                                maxBefore + damage };
        const float wanted = WantedDamage(before_, maxBefore + rise);

        if (a_av == RE::ActorValue::kHealth && before_.current > 0.0f && before_.current + a_delta <= 0.0f) {
            ++g_deaths;
            logger::info("{}: max {:.1f} -> {:.1f}, current {:.1f} held, vanilla would give {:.1f}. Death prevented.",
                         Util::Who(a_actor), maxBefore, maxBefore + a_delta, before_.current,
                         before_.current + a_delta);
        }

        if (std::abs(wanted - damage) < 0.001f) {
            return false;
        }

        // Raw rather than through ModActorValue, which would re-enter the function this hook sits inside
        slots->modifiers[MOD::kDamage] = wanted;
        InvalidateCached(a_actor, a_av);
        ++g_corrected;

        if (spdlog::should_log(spdlog::level::debug)) {
            logger::debug("{} av {}: {} {:.1f} -> {:.1f}, fortify part {:.1f}, damage {:.1f} -> {:.1f}",
                          Util::Who(a_actor), static_cast<int>(a_av),
                          a_mod == MOD::kPermanent ? "perm" : "temp", before, before + a_delta, rise, damage,
                          wanted);
        }

        return true;
    }

    template <std::size_t Index>
    struct ModifierCallHook
    {
        static void thunk(RE::Actor* a_actor, MOD a_mod, RE::ActorValue a_av, float a_delta, RE::Actor* a_source)
        {
            const bool wrote = OnModifierChange(a_actor, a_mod, a_av, a_delta);
            func(a_actor, a_mod, a_av, a_delta, a_source);

            // A raw write buys the number without the engine's bookkeeping, so regeneration is never armed. The round trip nets to zero while making two real calls
            // After the original, because ModActorValue re-enters the function this hook sits inside
            if (wrote && a_actor) {
                auto* owner = a_actor->AsActorValueOwner();
                owner->ModActorValue(MOD::kDamage, a_av, ARM_NUDGE);
                owner->ModActorValue(MOD::kDamage, a_av, -ARM_NUDGE);
            }
        }

        static inline REL::Relocation<decltype(thunk)> func;
    };

#ifdef FF_DEBUG_PANEL
    std::atomic_int32_t g_snapsRemaining{ 0 };
    std::chrono::steady_clock::time_point g_lastSnap{};

    // Time sampled as well as event driven, so a cause that stops the function being called still leaves evidence
    struct SnapshotTickHook
    {
        static void thunk()
        {
            func();

            if (g_snapsRemaining <= 0) {
                return;
            }
            if (auto* ui = RE::UI::GetSingleton(); !ui || ui->GameIsPaused()) {
                return;
            }

            const auto now = std::chrono::steady_clock::now();
            if (std::chrono::duration<float>(now - g_lastSnap).count() < 0.5f) {
                return;
            }
            g_lastSnap = now;
            --g_snapsRemaining;
            LogSnapshot("tick");
        }

        static inline REL::Relocation<decltype(thunk)> func;
    };
#endif

    // Addresses from virt-x/FortifyAttributeFix/plugin.cpp
    void ResolvePublishedSites()
    {
        g_publishedSites[0] = REL::RelocationID(34284, 35084).address() + 0x9e;
        g_publishedSites[1] = REL::Relocation<std::uintptr_t>(REL::VariantID(34284, 35084, 34284),
                                                              REL::VariantOffset(0x117, 0x119, 0x117))
                                  .address();
        g_publishedSites[2] = REL::Relocation<std::uintptr_t>(REL::VariantID(34286, 35086, 34286),
                                                              REL::VariantOffset(0x2d1, 0x2cc, 0x2d1))
                                  .address();
        g_publishedSites[3] = REL::Relocation<std::uintptr_t>(REL::VariantID(36345, 37335, 36345),
                                                              REL::VariantOffset(0x11d, 0x151, 0x11d))
                                  .address();
        g_publishedSites[4] = REL::Relocation<std::uintptr_t>(REL::VariantID(37633, 38586, 37633),
                                                              REL::VariantOffset(0x601, 0x70c, 0x601))
                                  .address();
    }

    template <std::size_t I>
    bool InstallAt(std::size_t a_index, std::uintptr_t a_address)
    {
        if (a_index != I) {
            return false;
        }
        ModifierCallHook<I>::func = SKSE::GetTrampoline().write_call<5>(a_address, ModifierCallHook<I>::thunk);
        return true;
    }

    template <std::size_t... I>
    void InstallOne(std::size_t a_index, std::uintptr_t a_address, std::index_sequence<I...>)
    {
        (InstallAt<I>(a_index, a_address) || ...);
    }

    // Covers all possible call sites from max and logs them
    void HookCallSites()
    {
        for (auto& site : g_callSites) {
            if (g_installed >= MAX_CALL_SITES) {
                logger::warn("Fortify: more call sites than hooks, {} left unhooked.",
                             g_callSites.size() - g_installed);
                break;
            }
            InstallOne(g_installed, site.address, std::make_index_sequence<MAX_CALL_SITES>{});
            ++g_installed;
            site.hooked = true;
        }
        logger::info("Fortify: {} of {} call sites hooked.", g_installed, g_callSites.size());
    }

    [[nodiscard]] bool IsCallSite(std::uintptr_t a_site)
    {
        const auto text = REL::Module::get().segment(REL::Segment::textx);
        if (!a_site || a_site < text.address() || a_site + 5 > text.address() + text.size()) {
            return false;
        }
        return *reinterpret_cast<const std::uint8_t*>(a_site) == 0xE8;
    }

    void HookPublishedFallback()
    {
        if (REL::Module::IsVR()) {
            logger::warn("Fortify: not falling back on VR, four of the published addresses carry an SE id in VariantID's VR slot.");
            return;
        }

        const auto base = REL::Module::get().base();
        for (const auto published : g_publishedSites) {
            if (!published || g_installed >= MAX_CALL_SITES) {
                continue;
            }

            bool already = false;
            for (const auto& site : g_callSites) {
                if (site.address == published) already = true;
            }
            if (already) {
                continue;
            }

            // An id plus a hand written offset, so a game update can leave these pointing at anything
            if (!IsCallSite(published)) {
                logger::error("Fortify: published site SkyrimSE.exe+{:X} is not a call instruction, refusing to hook it.",
                              published - base);
                continue;
            }

            InstallOne(g_installed, published, std::make_index_sequence<MAX_CALL_SITES>{});
            ++g_installed;
            g_callSites.push_back({ published - base, published, true, true });
            logger::warn("Fortify: fell back to published site SkyrimSE.exe+{:X}, the scan did not find it.",
                         published - base);
        }
    }

    // Logs a call site that was hooked by some other mod, at least it should. This makes my life easier
    std::string WhoTookIt(std::uintptr_t a_site)
    {
        if (*reinterpret_cast<const std::uint8_t*>(a_site) != 0xE8) {
            return "It is not a call instruction at all.";
        }

        std::int32_t rel{};
        std::memcpy(&rel, reinterpret_cast<const void*>(a_site + 1), sizeof(rel));
        const auto dest = a_site + 5 + static_cast<std::intptr_t>(rel);

        REX::W32::MEMORY_BASIC_INFORMATION info{};
        if (REX::W32::VirtualQuery(reinterpret_cast<const void*>(dest), &info, sizeof(info)) == 0 ||
            !info.allocationBase) {
            return std::format("It calls {:X}, which is in no mapped image. Probably a trampoline.", dest);
        }

        char path[MODULE_PATH_MAX]{};
        REX::W32::GetModuleFileNameA(static_cast<REX::W32::HMODULE>(info.allocationBase), path,
                                     MODULE_PATH_MAX);

        std::string name{ path };
        if (const auto slash = name.find_last_of(char{ 0x5C }); slash != std::string::npos) {
            name = name.substr(slash + 1);
        }
        return std::format("It calls into {}.", name.empty() ? "an unnamed module" : name);
    }

    void ScanCallSitesNow()
    {
        const auto target = REL::Relocation<std::uintptr_t>(RELOCATION_ID(37523, 38468)).address();
        const auto text = REL::Module::get().segment(REL::Segment::textx);
        const auto begin = text.address();
        const auto size = text.size();
        if (!target || !begin || size < 5) {
            logger::warn("Fortify: cannot scan, .text or the target did not resolve.");
            return;
        }

        // A resolved address outside executable code means the wrong address library answered (ItzIvy05/AutomaticallyLoweredWeapons/src/LowerWeapon.cpp:361-367)
        if (target < begin || target >= begin + size) {
            logger::error("Fortify: the modifier function resolved to {:X}, outside .text. Not scanning.", target);
            return;
        }

        const auto base = REL::Module::get().base();
        const auto* bytes = reinterpret_cast<const std::uint8_t*>(begin);

        for (std::size_t i = 0; i + 5 <= size; ++i) {
            if (bytes[i] != 0xE8) {
                continue;
            }

            std::int32_t rel{};
            std::memcpy(&rel, bytes + i + 1, sizeof(rel));
            const std::uintptr_t here = begin + i;
            if (here + 5 + static_cast<std::intptr_t>(rel) != target) {
                continue;
            }

            Fortify::CallSite site{ here - base, here, false, false };
            for (const auto published : g_publishedSites) {
                if (published == here) site.published = true;
            }
            g_callSites.push_back(site);
        }

        std::size_t published = 0;
        for (const auto& site : g_callSites) {
            if (site.published) ++published;
        }

        logger::info("Fortify: {} call sites of the modifier function in .text, {} of them published by the original.",
                     g_callSites.size(), published);
        for (const auto& site : g_callSites) {
            logger::debug("Fortify: call site SkyrimSE.exe+{:X}{}", site.offset,
                          site.published ? "" : "  (not in the original)");
        }
        for (const auto site : g_publishedSites) {
            bool real = false;
            for (const auto& found : g_callSites) {
                if (found.address == site) real = true;
            }
            if (site && !real) {
                logger::warn("Fortify: published site SkyrimSE.exe+{:X} is not a call to that function. {}",
                             site - base, WhoTookIt(site));
            }
        }
    }
}

namespace Fortify
{
    std::vector<CallSite> GetCallSites()
    {
        return g_callSites;
    }

    void StartStateLog([[maybe_unused]] std::int32_t a_samples)
    {
#ifdef FF_DEBUG_PANEL
        g_stateLogRemaining = a_samples;
        g_snapsRemaining = a_samples / 4;
        g_lastSnap = {};
        LogSnapshot("armed");
        logger::info("Fortify: logging the next {} modifier changes on the player, and sampling twice a second.",
                     a_samples);
#endif
    }

    void LogStats()
    {
        logger::info("Fortify: {} modifier changes seen, {} corrected, {} left alone, {} deaths prevented.",
                     g_seen.load(), g_corrected.load(), g_restores.load(), g_deaths.load());
    }

    void Install()
    {
        SKSE::AllocTrampoline(1 << 7);

        // Hooking what is verified rather than the original mod's addresses, four of which carry an SE id in VariantID's VR slot and resolve to a raw module offset there
        ResolvePublishedSites();
        ScanCallSitesNow();
        HookCallSites();

        // Six were counted against the unpacked 1.6.1170 exe, so it is only a expectation on AE
        if (REL::Module::IsAE() && g_installed < EXPECTED_CALL_SITES) {
            logger::warn("Fortify: expected {} call sites, hooked {}. Another plugin may have hooked one first.",
                         EXPECTED_CALL_SITES, g_installed);
            HookPublishedFallback();
        }

        if (g_installed == 0) {
            logger::warn("Fortify: no call sites hooked. The effect vtables are carrying this alone.");
        }

#ifdef FF_DEBUG_PANEL
        // Only the debug build polls, and only while a burst is armed. The published offsets here are SE and AE
        if (!REL::Module::IsVR()) {
            REL::Relocation<std::uintptr_t> mainUpdate{ RELOCATION_ID(35565, 36564), REL::Relocate(0x748, 0xC26) };
            SnapshotTickHook::func = SKSE::GetTrampoline().write_call<5>(mainUpdate.address(), SnapshotTickHook::thunk);
            logger::info("Fortify: snapshot tick hooked, idle until a burst is armed.");
        }
#endif
    }

    void OnGameLoaded()
    {
    }

    void LoadSettings()
    {
        const auto mode = static_cast<int>(Settings::GetSetting("Mode", 0.0f));
        g_mode = mode == 1   ? Mode::kRatio
                 : mode == 2 ? Mode::kOff
                 : mode == 3 ? Mode::kRestore
                             : Mode::kAbsolute;
        g_playerOnly = Settings::GetSetting("PlayerOnly", 0.0f) != 0.0f;

        logger::info("Fortify: mode {}, {}.", static_cast<int>(g_mode.load()),
                     g_playerOnly.load() ? "player only" : "every actor");
        LogStats();
    }

    Mode CurrentMode()
    {
        return g_mode.load();
    }

    void SetMode(Mode a_mode)
    {
        g_mode = a_mode;
        logger::info("Fortify: mode set to {} from the menu.", static_cast<int>(a_mode));
        LogStats();
    }

    bool PlayerOnly()
    {
        return g_playerOnly.load();
    }

    void SetPlayerOnly(bool a_value)
    {
        g_playerOnly = a_value;
    }

    Stats GetStats()
    {
        return { g_seen.load(), g_corrected.load(), g_restores.load(), g_deaths.load() };
    }
}
